src: "src"
data: "data"
templates: "templates"
input: "input"
output: "output"
images: "report_images"
loan_json_file: "loan_field_data.json"
credit_excel_file: "credit_report.xlsx"
output_file: "{report_prefix}_{month_label}_{year_label}.docx"
appendix_template_file: "{report_prefix}_appendix.docx"
doc_template_file: "{report_prefix}.docx"
credentials_file: "credentials.json"