api_server: "https://encompass.elliemae.com"
token_url: "{api_server}/oauth2/v1/token"
pipeline_url: "{api_server}/encompass/v3/loanPipeline?start=0&limit=1000"
fields:
  - "Loan.LoanFolder"
  - "Fields.4000"
  - "Loan.LoanNumber"
  - "Loan.LoanRate"
  - "Loan.LoanAmount"
  - "Loan.LastModified"
  - "Loan.BorrowerName"
sort_order:
  - "canonicalName": "Loan.LastModified"
    "order": "Descending"
field_ids:
  - "2626"
  - "317"
  - "LoanTeamMember.Name.Underwriter"
  - "LoanTeamMember.Name.Branch Processor" 
  - "2"
  - "1401"
  - "14"
  - "411"
  - "1997"
  - "Log.MS.Date.Sent to Branch LP"
  - "Log.MS.Date.Clear to Close"
  - "ORGID"
  - "Log.MS.Date.Dislosures Returned"
  - "Log.MS.Date.Submittal"
  - "Log.MS.Date.TPO Submit"
date_fields:
  - "1997"
  - "Log.MS.Date.Sent to Branch LP"
  - "Log.MS.Date.Clear to Close"
  - "Log.MS.Date.Dislosures Returned"
  - "Log.MS.Date.Submittal"
  - "Log.MS.Date.TPO Submit"
folders:
  - "Active Pipeline"
  - "Closed 2025"